import{a as L,S as P,i as h}from"./assets/vendor-u8rapaCG.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const S="https://pixabay.com/api/",$="46160899-12bbcf382b0949676f8e01c93";async function m({query:e,page:t=1}){try{const o=await L.get(`${S}`,{params:{key:$,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}});if(o.data.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return o.data}catch(o){throw o.response?new Error(`Server Error: ${o.response.status} - ${o.response.statusText}`):o.request?new Error("Network error occurred. Please check your connection or try again later."):new Error(`Error: ${o.message}`)}}function v(e){e.innerHTML=""}function p(e,t){const o=e.map(({webformatURL:a,largeImageURL:r,tags:s,likes:n,views:w,comments:E,downloads:q})=>`
    <li class ="gallery-item">
      <a href="${r}" class="gallery-link">
        <img src="${a}" alt="${s}" class="gallery-image" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${n}</p>
          <p class="info-item"><b>Views:</b> ${w}</p>
          <p class="info-item"><b>Comments:</b> ${E}</p>
          <p class="info-item"><b>Downloads:</b> ${q}</p>
        </div>
      </a>
      </li>`).join("");t.insertAdjacentHTML("beforeend",o)}const I=document.querySelector(".search-form"),d=document.querySelector(".gallery"),u=document.querySelector(".load-more"),f=document.querySelector(".loader"),g=new P(".gallery a",{captionsData:"alt",captionDelay:250});let l="",i=1;const b=15;let c=0;function y(e){h.error({title:"Error",message:e})}function O(e){h.info({title:"Info",message:e})}I.addEventListener("submit",async e=>{if(e.preventDefault(),l=e.target.elements.searchQuery.value.trim(),!l){y("Please enter a search term.");return}i=1,v(d),u.style.display="none",c=0;try{f.style.display="block";const t=await m({query:l,page:i});c=t.totalHits,t.hits.length===0?y("Sorry, there are no images matching your search query. Please try again!"):(p(t.hits,d),g.refresh(),u.style.display=c>b?"block":"none")}catch(t){y(t.message)}finally{f.style.display="none"}});u.addEventListener("click",async()=>{i+=1;try{f.style.display="block";const e=await m({query:l,page:i});if(e.hits.length>0){p(e.hits,d),g.refresh();const t=document.querySelector(".gallery-item");if(t){const{height:a}=t.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}const o=Math.ceil(c/b);i>=o&&(u.style.display="none",O("We're sorry, but you've reached the end of search results."))}}catch(e){y(`Error fetching more images: ${e.message}`)}finally{f.style.display="none"}});
//# sourceMappingURL=index.js.map
